//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("devexpress.build.xamlresourceprocessing.targets")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("controls/datagridtestclasses.dbml.layout")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("controls/datagridtestclasses.dbml")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("dll/devexpress.mvvm.roslyn.dll")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("dll/entityframework.dll")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("dll/system.data.sqlite.dll")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("dll/system.data.sqlite.ef6.dll")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("dll/wpf/system.windows.interactivity.dll")]


