using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.Ribbon;

namespace RibbonDemo {
    [NoAutogeneratedCodeFiles]
    public class RibbonOffice2007 : RibbonSimplePad {
        public RibbonOffice2007() { }
        protected override RibbonStyle GetRibbonStyle() {
            return RibbonStyle.Office2007;
        }
    }
}
