#pragma checksum "..\..\..\Modules\AdvancedPrintingOptions.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "C52EE1EE467A3ED4F276792F80C7B6AC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Core;
using DevExpress.DemoData;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Core.ConditionalFormatting;
using DevExpress.Xpf.Core.DataSources;
using DevExpress.Xpf.Core.Serialization;
using DevExpress.Xpf.Core.ServerMode;
using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.DemoBase.DataClasses;
using DevExpress.Xpf.DemoBase.Helpers;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.ConditionalFormatting;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.Themes;
using DevExpress.Xpf.Grid.TreeList;
using DevExpress.Xpf.Printing;
using GridDemo;
using System;
using System.Collections;
using System.Diagnostics;
using System.Globalization;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace GridDemo {
    
    
    /// <summary>
    /// AdvancedPrintingOptions
    /// </summary>
    public partial class AdvancedPrintingOptions : GridDemo.PrintViewGridDemoModule, System.Windows.Markup.IComponentConnector {
        
        
        #line 45 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ListBoxEdit printStyleChooser;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button newTabButton;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button newWindowButton;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Core.DXTabControl tabControl;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl grid;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn countryColumn;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn cityColumn;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn unitPriceColumn;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.TableView view;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/GridDemo;component/modules/advancedprintingoptions.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.printStyleChooser = ((DevExpress.Xpf.Editors.ListBoxEdit)(target));
            
            #line 45 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
            this.printStyleChooser.EditValueChanged += new DevExpress.Xpf.Editors.EditValueChangedEventHandler(this.printStyleChooser_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.newTabButton = ((System.Windows.Controls.Button)(target));
            
            #line 55 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
            this.newTabButton.Click += new System.Windows.RoutedEventHandler(this.newTabButton_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.newWindowButton = ((System.Windows.Controls.Button)(target));
            
            #line 58 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
            this.newWindowButton.Click += new System.Windows.RoutedEventHandler(this.newWindowButton_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.tabControl = ((DevExpress.Xpf.Core.DXTabControl)(target));
            
            #line 63 "..\..\..\Modules\AdvancedPrintingOptions.xaml"
            this.tabControl.TabHidden += new DevExpress.Xpf.Core.TabControlTabHiddenEventHandler(this.tabControl_TabHidden);
            
            #line default
            #line hidden
            return;
            case 5:
            this.grid = ((DevExpress.Xpf.Grid.GridControl)(target));
            return;
            case 6:
            this.countryColumn = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 7:
            this.cityColumn = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 8:
            this.unitPriceColumn = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 9:
            this.view = ((DevExpress.Xpf.Grid.TableView)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

