#pragma checksum "..\..\..\Modules\BindingToDynamicObject.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "427EC96ACB6E2D43609376775723F478"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Core;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Core.ConditionalFormatting;
using DevExpress.Xpf.Core.DataSources;
using DevExpress.Xpf.Core.Serialization;
using DevExpress.Xpf.Core.ServerMode;
using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.DemoBase.DataClasses;
using DevExpress.Xpf.DemoBase.Helpers;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.ConditionalFormatting;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.TreeList;
using GridDemo;
using System;
using System.Collections;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace GridDemo {
    
    
    /// <summary>
    /// BindingToDynamicObject
    /// </summary>
    public partial class BindingToDynamicObject : GridDemo.GridDemoModule, System.Windows.Markup.IComponentConnector {
        
        
        #line 20 "..\..\..\Modules\BindingToDynamicObject.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel optionsPanel;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\Modules\BindingToDynamicObject.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit FieldNameBox;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\Modules\BindingToDynamicObject.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ComboBoxEdit TypeBox;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\Modules\BindingToDynamicObject.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.SpinEdit DefaultValueBoxSpin;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\Modules\BindingToDynamicObject.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit DefaultValueBoxText;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\Modules\BindingToDynamicObject.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.DateEdit DefaultValueBoxDate;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\Modules\BindingToDynamicObject.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit DefaultValueBoxCheck;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\Modules\BindingToDynamicObject.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CreateNewColBtn;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\Modules\BindingToDynamicObject.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl grid;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\Modules\BindingToDynamicObject.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.TableView View;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/GridDemo;component/modules/bindingtodynamicobject.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Modules\BindingToDynamicObject.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.optionsPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 2:
            this.FieldNameBox = ((DevExpress.Xpf.Editors.TextEdit)(target));
            
            #line 24 "..\..\..\Modules\BindingToDynamicObject.xaml"
            this.FieldNameBox.Validate += new DevExpress.Xpf.Editors.Validation.ValidateEventHandler(this.FieldNameBox_Validate);
            
            #line default
            #line hidden
            return;
            case 3:
            this.TypeBox = ((DevExpress.Xpf.Editors.ComboBoxEdit)(target));
            return;
            case 4:
            this.DefaultValueBoxSpin = ((DevExpress.Xpf.Editors.SpinEdit)(target));
            return;
            case 5:
            this.DefaultValueBoxText = ((DevExpress.Xpf.Editors.TextEdit)(target));
            return;
            case 6:
            this.DefaultValueBoxDate = ((DevExpress.Xpf.Editors.DateEdit)(target));
            return;
            case 7:
            this.DefaultValueBoxCheck = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            return;
            case 8:
            this.CreateNewColBtn = ((System.Windows.Controls.Button)(target));
            
            #line 87 "..\..\..\Modules\BindingToDynamicObject.xaml"
            this.CreateNewColBtn.Click += new System.Windows.RoutedEventHandler(this.CreateNewColBtn_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.grid = ((DevExpress.Xpf.Grid.GridControl)(target));
            return;
            case 10:
            this.View = ((DevExpress.Xpf.Grid.TableView)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

