#pragma checksum "..\..\..\Modules\BuiltInContextMenus.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "D0160D9D47450B76BAE64E2E59ECD8A4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Core;
using DevExpress.DemoData;
using DevExpress.Xpf.Bars;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Core.ConditionalFormatting;
using DevExpress.Xpf.Core.DataSources;
using DevExpress.Xpf.Core.Serialization;
using DevExpress.Xpf.Core.ServerMode;
using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.DemoBase.DataClasses;
using DevExpress.Xpf.DemoBase.Helpers;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.ConditionalFormatting;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.TreeList;
using GridDemo;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace GridDemo {
    
    
    /// <summary>
    /// BuiltInContextMenus
    /// </summary>
    public partial class BuiltInContextMenus : GridDemo.GridDemoModule, System.Windows.Markup.IComponentConnector {
        
        
        #line 1 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal GridDemo.BuiltInContextMenus ContextMenuModule;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit columnMenuRemoveItemCheck;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit columnMenuAddItemCheck;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit groupPanelMenuRemoveItemCheck;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit groupPanelMenuAddItemCheck;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit totalMenuRemoveItemCheck;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarManager barManager;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem copyCellDataItem;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem copyRowDataItem;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem deleteRowItem;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl grid;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn colCountry;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn colUnitPrice;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.TableView view;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarCheckItem allowSortingItem;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarCheckItem allowGroupingItem;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarCheckItem allowAllSortingItem;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarCheckItem allowAllGroupingItem;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarSubItem copyInfoItem;
        
        #line default
        #line hidden
        
        
        #line 108 "..\..\..\Modules\BuiltInContextMenus.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarCheckItem customSummaryMenuItem;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/GridDemo;component/modules/builtincontextmenus.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Modules\BuiltInContextMenus.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ContextMenuModule = ((GridDemo.BuiltInContextMenus)(target));
            return;
            case 2:
            this.columnMenuRemoveItemCheck = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            return;
            case 3:
            this.columnMenuAddItemCheck = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            return;
            case 4:
            this.groupPanelMenuRemoveItemCheck = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            return;
            case 5:
            this.groupPanelMenuAddItemCheck = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            return;
            case 6:
            this.totalMenuRemoveItemCheck = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            return;
            case 7:
            this.barManager = ((DevExpress.Xpf.Bars.BarManager)(target));
            return;
            case 8:
            this.copyCellDataItem = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 9:
            this.copyRowDataItem = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 10:
            this.deleteRowItem = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 11:
            this.grid = ((DevExpress.Xpf.Grid.GridControl)(target));
            
            #line 60 "..\..\..\Modules\BuiltInContextMenus.xaml"
            this.grid.CustomSummary += new DevExpress.Data.CustomSummaryEventHandler(this.grid_CustomSummary);
            
            #line default
            #line hidden
            
            #line 60 "..\..\..\Modules\BuiltInContextMenus.xaml"
            this.grid.CustomSummaryExists += new DevExpress.Data.CustomSummaryExistEventHandler(this.grid_CustomSummaryExists);
            
            #line default
            #line hidden
            return;
            case 12:
            this.colCountry = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 13:
            this.colUnitPrice = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 14:
            this.view = ((DevExpress.Xpf.Grid.TableView)(target));
            
            #line 84 "..\..\..\Modules\BuiltInContextMenus.xaml"
            this.view.ShowGridMenu += new DevExpress.Xpf.Grid.GridMenuEventHandler(this.TableView_ShowGridMenu);
            
            #line default
            #line hidden
            return;
            case 15:
            this.allowSortingItem = ((DevExpress.Xpf.Bars.BarCheckItem)(target));
            return;
            case 16:
            this.allowGroupingItem = ((DevExpress.Xpf.Bars.BarCheckItem)(target));
            return;
            case 17:
            this.allowAllSortingItem = ((DevExpress.Xpf.Bars.BarCheckItem)(target));
            return;
            case 18:
            this.allowAllGroupingItem = ((DevExpress.Xpf.Bars.BarCheckItem)(target));
            return;
            case 19:
            this.copyInfoItem = ((DevExpress.Xpf.Bars.BarSubItem)(target));
            return;
            case 20:
            this.customSummaryMenuItem = ((DevExpress.Xpf.Bars.BarCheckItem)(target));
            
            #line 108 "..\..\..\Modules\BuiltInContextMenus.xaml"
            this.customSummaryMenuItem.CheckedChanged += new DevExpress.Xpf.Bars.ItemClickEventHandler(this.customSummaryMenuItem_CheckedChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

