#pragma checksum "..\..\..\Modules\CardView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "FB2073BB79159BCC7152732F7C58B7D6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Core;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Core.ConditionalFormatting;
using DevExpress.Xpf.Core.DataSources;
using DevExpress.Xpf.Core.Serialization;
using DevExpress.Xpf.Core.ServerMode;
using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.DemoBase.DataClasses;
using DevExpress.Xpf.DemoBase.Helpers;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.ConditionalFormatting;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.TreeList;
using GridDemo;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace GridDemo {
    
    
    /// <summary>
    /// CardView
    /// </summary>
    public partial class CardView : GridDemo.GridDemoModule, System.Windows.Markup.IComponentConnector {
        
        
        #line 47 "..\..\..\Modules\CardView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton maxCardCountInRowNoLimitRadioButton;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\Modules\CardView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton maxCardCountInRowValueRadioButton;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\Modules\CardView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.SpinEdit maxCardCountInRowSpinEdit;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\Modules\CardView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ListBoxEdit NavigationStyleComboBox;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\Modules\CardView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl grid;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\Modules\CardView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.CardView view;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/GridDemo;component/modules/cardview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Modules\CardView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 34 "..\..\..\Modules\CardView.xaml"
            ((DevExpress.Xpf.Editors.ComboBoxEdit)(target)).EditValueChanged += new DevExpress.Xpf.Editors.EditValueChangedEventHandler(this.ComboBoxEdit_EditValueChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.maxCardCountInRowNoLimitRadioButton = ((System.Windows.Controls.RadioButton)(target));
            
            #line 47 "..\..\..\Modules\CardView.xaml"
            this.maxCardCountInRowNoLimitRadioButton.Checked += new System.Windows.RoutedEventHandler(this.maxCardCountInRowNoLimitRadioButton_Checked);
            
            #line default
            #line hidden
            return;
            case 3:
            this.maxCardCountInRowValueRadioButton = ((System.Windows.Controls.RadioButton)(target));
            
            #line 48 "..\..\..\Modules\CardView.xaml"
            this.maxCardCountInRowValueRadioButton.Checked += new System.Windows.RoutedEventHandler(this.maxCardCountInRowValueRadioButton_Checked);
            
            #line default
            #line hidden
            return;
            case 4:
            this.maxCardCountInRowSpinEdit = ((DevExpress.Xpf.Editors.SpinEdit)(target));
            
            #line 49 "..\..\..\Modules\CardView.xaml"
            this.maxCardCountInRowSpinEdit.EditValueChanged += new DevExpress.Xpf.Editors.EditValueChangedEventHandler(this.maxCardCountInRowSpinEdit_EditValueChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.NavigationStyleComboBox = ((DevExpress.Xpf.Editors.ListBoxEdit)(target));
            return;
            case 6:
            this.grid = ((DevExpress.Xpf.Grid.GridControl)(target));
            return;
            case 7:
            this.view = ((DevExpress.Xpf.Grid.CardView)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

