#pragma checksum "..\..\..\Modules\CardWinExplorer.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "1930878F4998829A984205BEF3BBD55B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Core;
using DevExpress.Xpf.Bars;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Core.ConditionalFormatting;
using DevExpress.Xpf.Core.DataSources;
using DevExpress.Xpf.Core.Serialization;
using DevExpress.Xpf.Core.ServerMode;
using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.DemoBase.DataClasses;
using DevExpress.Xpf.DemoBase.Helpers;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.ConditionalFormatting;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.TreeList;
using GridDemo;
using GridDemo.ModuleResources;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace GridDemo {
    
    
    /// <summary>
    /// CardWinExplorer
    /// </summary>
    public partial class CardWinExplorer : GridDemo.GridDemoModule, System.Windows.Markup.IComponentConnector {
        
        
        #line 34 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbExrtaLarge;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbLarge;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbMedium;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbGroupName;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbGroupType;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbGroupNone;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem bBack;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem bForward;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem bUp;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit tbPath;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.SearchControl tbSearch;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl Grid;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn columnName;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn columnType;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn columnNameFirst;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\Modules\CardWinExplorer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.CardView View;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/GridDemo;component/modules/cardwinexplorer.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Modules\CardWinExplorer.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.rbExrtaLarge = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 2:
            this.rbLarge = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 3:
            this.rbMedium = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 4:
            this.rbGroupName = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 5:
            this.rbGroupType = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 6:
            this.rbGroupNone = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 7:
            this.bBack = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 8:
            this.bForward = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 9:
            this.bUp = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 10:
            this.tbPath = ((DevExpress.Xpf.Editors.TextEdit)(target));
            return;
            case 11:
            this.tbSearch = ((DevExpress.Xpf.Editors.SearchControl)(target));
            return;
            case 12:
            this.Grid = ((DevExpress.Xpf.Grid.GridControl)(target));
            return;
            case 13:
            this.columnName = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 14:
            this.columnType = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 15:
            this.columnNameFirst = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 16:
            this.View = ((DevExpress.Xpf.Grid.CardView)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

