#pragma checksum "..\..\..\Modules\ColumnCustomization.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "53DA92FBDBB9EFCBE299F2A1921EC70A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Core;
using DevExpress.DemoData;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Core.ConditionalFormatting;
using DevExpress.Xpf.Core.DataSources;
using DevExpress.Xpf.Core.Serialization;
using DevExpress.Xpf.Core.ServerMode;
using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.DemoBase.DataClasses;
using DevExpress.Xpf.DemoBase.Helpers;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Themes;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.ConditionalFormatting;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.TreeList;
using GridDemo;
using System;
using System.Collections;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace GridDemo {
    
    
    /// <summary>
    /// ColumnCustomization
    /// </summary>
    public partial class ColumnCustomization : GridDemo.GridDemoModule, System.Windows.Markup.IComponentConnector {
        
        
        #line 34 "..\..\..\Modules\ColumnCustomization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton showHideButton;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\Modules\ColumnCustomization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ListBoxEdit columnChooserTypesListBox;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\Modules\ColumnCustomization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.DemoBase.DemoExpander customColumnChooserExpander;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\Modules\ColumnCustomization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal GridDemo.DemoColumnChooserControl columnChooser;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\Modules\ColumnCustomization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl grid;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\Modules\ColumnCustomization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.TableView gridView;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/GridDemo;component/modules/columncustomization.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Modules\ColumnCustomization.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.showHideButton = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            
            #line 37 "..\..\..\Modules\ColumnCustomization.xaml"
            this.showHideButton.Checked += new System.Windows.RoutedEventHandler(this.showHideButton_Toggle);
            
            #line default
            #line hidden
            
            #line 38 "..\..\..\Modules\ColumnCustomization.xaml"
            this.showHideButton.Unchecked += new System.Windows.RoutedEventHandler(this.showHideButton_Toggle);
            
            #line default
            #line hidden
            return;
            case 2:
            this.columnChooserTypesListBox = ((DevExpress.Xpf.Editors.ListBoxEdit)(target));
            return;
            case 3:
            this.customColumnChooserExpander = ((DevExpress.Xpf.DemoBase.DemoExpander)(target));
            
            #line 53 "..\..\..\Modules\ColumnCustomization.xaml"
            this.customColumnChooserExpander.Expanded += new System.Windows.RoutedEventHandler(this.customColumnChooserExpander_Expanded);
            
            #line default
            #line hidden
            
            #line 54 "..\..\..\Modules\ColumnCustomization.xaml"
            this.customColumnChooserExpander.Collapsed += new System.Windows.RoutedEventHandler(this.customColumnChooserExpander_Collapsed);
            
            #line default
            #line hidden
            return;
            case 4:
            this.columnChooser = ((GridDemo.DemoColumnChooserControl)(target));
            return;
            case 5:
            this.grid = ((DevExpress.Xpf.Grid.GridControl)(target));
            return;
            case 6:
            this.gridView = ((DevExpress.Xpf.Grid.TableView)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

