#pragma checksum "..\..\..\Modules\CopyPasteOperations.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "12A7EA9BF39F036959A350C6CD3F7D72"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Core;
using DevExpress.Xpf.Bars;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Core.ConditionalFormatting;
using DevExpress.Xpf.Core.DataSources;
using DevExpress.Xpf.Core.Serialization;
using DevExpress.Xpf.Core.ServerMode;
using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.DemoBase.DataClasses;
using DevExpress.Xpf.DemoBase.Helpers;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.ConditionalFormatting;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.Themes;
using DevExpress.Xpf.Grid.TreeList;
using GridDemo;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace GridDemo {
    
    
    /// <summary>
    /// CopyPasteOperations
    /// </summary>
    public partial class CopyPasteOperations : GridDemo.GridDemoModule, System.Windows.Markup.IComponentConnector {
        
        
        #line 32 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit allowCopyingtoClipboardCheckEdit;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit copyHeaderCheckEdit;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ListBoxEdit PasteRule;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CopyButton;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CutButton;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PasteButton;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DeleteButton;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem gridCopy;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem gridCut;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem gridPaste;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem gridDelete;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid DemoContentGrid;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl firstGrid;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.PopupMenu firstPopupMenu;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem viewFirstCopy;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem viewFirstCut;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem viewFirstPaste;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem viewFirstDelete;
        
        #line default
        #line hidden
        
        
        #line 108 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl CopyPasteDemoTabControl;
        
        #line default
        #line hidden
        
        
        #line 111 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl secondGrid;
        
        #line default
        #line hidden
        
        
        #line 119 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.PopupMenu secondPopupMenu;
        
        #line default
        #line hidden
        
        
        #line 143 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem viewSecondCopy;
        
        #line default
        #line hidden
        
        
        #line 144 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem viewSecondCut;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem viewSecondPaste;
        
        #line default
        #line hidden
        
        
        #line 146 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem viewSecondDelete;
        
        #line default
        #line hidden
        
        
        #line 154 "..\..\..\Modules\CopyPasteOperations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit textEdit;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/GridDemo;component/modules/copypasteoperations.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Modules\CopyPasteOperations.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 27 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.CopyCommandBinding_Executed);
            
            #line default
            #line hidden
            
            #line 27 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).CanExecute += new System.Windows.Input.CanExecuteRoutedEventHandler(this.CopyCommandBinding_CanExecute);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 28 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.CutCommandBinding_Executed);
            
            #line default
            #line hidden
            
            #line 28 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).CanExecute += new System.Windows.Input.CanExecuteRoutedEventHandler(this.CutCommandBinding_CanExecute);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 29 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.PasteCommandBinding_Executed);
            
            #line default
            #line hidden
            
            #line 29 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).CanExecute += new System.Windows.Input.CanExecuteRoutedEventHandler(this.PasteCommandBinding_CanExecute);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 30 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.DeleteCommandBinding_Executed);
            
            #line default
            #line hidden
            
            #line 30 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).CanExecute += new System.Windows.Input.CanExecuteRoutedEventHandler(this.DeleteCommandBinding_CanExecute);
            
            #line default
            #line hidden
            return;
            case 5:
            this.allowCopyingtoClipboardCheckEdit = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            
            #line 32 "..\..\..\Modules\CopyPasteOperations.xaml"
            this.allowCopyingtoClipboardCheckEdit.Checked += new System.Windows.RoutedEventHandler(this.allowCopyingtoClipboardCheckEdit_Checked);
            
            #line default
            #line hidden
            
            #line 32 "..\..\..\Modules\CopyPasteOperations.xaml"
            this.allowCopyingtoClipboardCheckEdit.Unchecked += new System.Windows.RoutedEventHandler(this.allowCopyingtoClipboardCheckEdit_Unchecked);
            
            #line default
            #line hidden
            return;
            case 6:
            this.copyHeaderCheckEdit = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            
            #line 33 "..\..\..\Modules\CopyPasteOperations.xaml"
            this.copyHeaderCheckEdit.Checked += new System.Windows.RoutedEventHandler(this.copyHeaderCheckEdit_Checked);
            
            #line default
            #line hidden
            
            #line 33 "..\..\..\Modules\CopyPasteOperations.xaml"
            this.copyHeaderCheckEdit.Unchecked += new System.Windows.RoutedEventHandler(this.copyHeaderCheckEdit_Unchecked);
            
            #line default
            #line hidden
            return;
            case 7:
            this.PasteRule = ((DevExpress.Xpf.Editors.ListBoxEdit)(target));
            return;
            case 8:
            this.CopyButton = ((System.Windows.Controls.Button)(target));
            return;
            case 9:
            this.CutButton = ((System.Windows.Controls.Button)(target));
            return;
            case 10:
            this.PasteButton = ((System.Windows.Controls.Button)(target));
            return;
            case 11:
            this.DeleteButton = ((System.Windows.Controls.Button)(target));
            return;
            case 12:
            this.gridCopy = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 13:
            this.gridCut = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 14:
            this.gridPaste = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 15:
            this.gridDelete = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 16:
            this.DemoContentGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 17:
            this.firstGrid = ((DevExpress.Xpf.Grid.GridControl)(target));
            
            #line 68 "..\..\..\Modules\CopyPasteOperations.xaml"
            this.firstGrid.CustomUnboundColumnData += new DevExpress.Xpf.Grid.GridColumnDataEventHandler(this.Grid_CustomUnboundColumnData);
            
            #line default
            #line hidden
            return;
            case 18:
            
            #line 70 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.CopyCommandBinding_Executed);
            
            #line default
            #line hidden
            
            #line 70 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).CanExecute += new System.Windows.Input.CanExecuteRoutedEventHandler(this.CopyCommandBinding_CanExecute);
            
            #line default
            #line hidden
            return;
            case 19:
            
            #line 71 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.CutCommandBinding_Executed);
            
            #line default
            #line hidden
            
            #line 71 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).CanExecute += new System.Windows.Input.CanExecuteRoutedEventHandler(this.CutCommandBinding_CanExecute);
            
            #line default
            #line hidden
            return;
            case 20:
            
            #line 72 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.PasteCommandBinding_Executed);
            
            #line default
            #line hidden
            
            #line 72 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).CanExecute += new System.Windows.Input.CanExecuteRoutedEventHandler(this.PasteCommandBinding_CanExecute);
            
            #line default
            #line hidden
            return;
            case 21:
            
            #line 73 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.DeleteCommandBinding_Executed);
            
            #line default
            #line hidden
            
            #line 73 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).CanExecute += new System.Windows.Input.CanExecuteRoutedEventHandler(this.DeleteCommandBinding_CanExecute);
            
            #line default
            #line hidden
            return;
            case 22:
            this.firstPopupMenu = ((DevExpress.Xpf.Bars.PopupMenu)(target));
            return;
            case 23:
            this.viewFirstCopy = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 24:
            this.viewFirstCut = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 25:
            this.viewFirstPaste = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 26:
            this.viewFirstDelete = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 27:
            this.CopyPasteDemoTabControl = ((System.Windows.Controls.TabControl)(target));
            return;
            case 28:
            this.secondGrid = ((DevExpress.Xpf.Grid.GridControl)(target));
            
            #line 111 "..\..\..\Modules\CopyPasteOperations.xaml"
            this.secondGrid.CustomUnboundColumnData += new DevExpress.Xpf.Grid.GridColumnDataEventHandler(this.Grid_CustomUnboundColumnData);
            
            #line default
            #line hidden
            return;
            case 29:
            
            #line 113 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.CopyCommandBinding_Executed);
            
            #line default
            #line hidden
            
            #line 113 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).CanExecute += new System.Windows.Input.CanExecuteRoutedEventHandler(this.CopyCommandBinding_CanExecute);
            
            #line default
            #line hidden
            return;
            case 30:
            
            #line 114 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.CutCommandBinding_Executed);
            
            #line default
            #line hidden
            
            #line 114 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).CanExecute += new System.Windows.Input.CanExecuteRoutedEventHandler(this.CutCommandBinding_CanExecute);
            
            #line default
            #line hidden
            return;
            case 31:
            
            #line 115 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.PasteCommandBinding_Executed);
            
            #line default
            #line hidden
            
            #line 115 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).CanExecute += new System.Windows.Input.CanExecuteRoutedEventHandler(this.PasteCommandBinding_CanExecute);
            
            #line default
            #line hidden
            return;
            case 32:
            
            #line 116 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.DeleteCommandBinding_Executed);
            
            #line default
            #line hidden
            
            #line 116 "..\..\..\Modules\CopyPasteOperations.xaml"
            ((System.Windows.Input.CommandBinding)(target)).CanExecute += new System.Windows.Input.CanExecuteRoutedEventHandler(this.DeleteCommandBinding_CanExecute);
            
            #line default
            #line hidden
            return;
            case 33:
            this.secondPopupMenu = ((DevExpress.Xpf.Bars.PopupMenu)(target));
            return;
            case 34:
            this.viewSecondCopy = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 35:
            this.viewSecondCut = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 36:
            this.viewSecondPaste = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 37:
            this.viewSecondDelete = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 38:
            this.textEdit = ((DevExpress.Xpf.Editors.TextEdit)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

