#pragma checksum "..\..\..\Modules\LINQToSQLServer.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "9372D64246B993698C4B7C07890A43D4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Core;
using DevExpress.Mvvm;
using DevExpress.Mvvm.UI;
using DevExpress.Mvvm.UI.Interactivity;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Core.ConditionalFormatting;
using DevExpress.Xpf.Core.DataSources;
using DevExpress.Xpf.Core.Serialization;
using DevExpress.Xpf.Core.ServerMode;
using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.DemoBase.DataClasses;
using DevExpress.Xpf.DemoBase.Helpers;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.ConditionalFormatting;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.Themes;
using DevExpress.Xpf.Grid.TreeList;
using GridDemo;
using GridDemo.Controls;
using System;
using System.Collections;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace GridDemo {
    
    
    /// <summary>
    /// LINQToSQLServer
    /// </summary>
    public partial class LINQToSQLServer : GridDemo.GridDemoModule, System.Windows.Markup.IComponentConnector {
        
        
        #line 29 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit chkInstantFeedBack;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnConfigure;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ListBoxEdit waitIndicatorList;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Core.ServerMode.LinqServerModeDataSource linqServerModeDataSource;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Core.ServerMode.LinqInstantFeedbackDataSource linqInstantFeedbackDataSource;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl grid;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn colid;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn colFrom;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn colSubject;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn colSent;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn colSize;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn colHasAttachment;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridColumn colDaysActive;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\Modules\LINQToSQLServer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.TableView view;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/GridDemo;component/modules/linqtosqlserver.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Modules\LINQToSQLServer.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.chkInstantFeedBack = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            
            #line 29 "..\..\..\Modules\LINQToSQLServer.xaml"
            this.chkInstantFeedBack.Checked += new System.Windows.RoutedEventHandler(this.ChangeInstantFeedBack);
            
            #line default
            #line hidden
            
            #line 29 "..\..\..\Modules\LINQToSQLServer.xaml"
            this.chkInstantFeedBack.Unchecked += new System.Windows.RoutedEventHandler(this.ChangeInstantFeedBack);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnConfigure = ((System.Windows.Controls.Button)(target));
            
            #line 30 "..\..\..\Modules\LINQToSQLServer.xaml"
            this.btnConfigure.Click += new System.Windows.RoutedEventHandler(this.Configure);
            
            #line default
            #line hidden
            return;
            case 3:
            this.waitIndicatorList = ((DevExpress.Xpf.Editors.ListBoxEdit)(target));
            
            #line 33 "..\..\..\Modules\LINQToSQLServer.xaml"
            this.waitIndicatorList.EditValueChanged += new DevExpress.Xpf.Editors.EditValueChangedEventHandler(this.CustomizeWaitIndicator);
            
            #line default
            #line hidden
            return;
            case 4:
            this.linqServerModeDataSource = ((DevExpress.Xpf.Core.ServerMode.LinqServerModeDataSource)(target));
            return;
            case 5:
            this.linqInstantFeedbackDataSource = ((DevExpress.Xpf.Core.ServerMode.LinqInstantFeedbackDataSource)(target));
            return;
            case 6:
            this.grid = ((DevExpress.Xpf.Grid.GridControl)(target));
            return;
            case 7:
            this.colid = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 8:
            this.colFrom = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 9:
            this.colSubject = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 10:
            this.colSent = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 11:
            this.colSize = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 12:
            this.colHasAttachment = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 13:
            this.colDaysActive = ((DevExpress.Xpf.Grid.GridColumn)(target));
            return;
            case 14:
            this.view = ((DevExpress.Xpf.Grid.TableView)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

