#pragma checksum "..\..\..\Modules\ManagingLiveData.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "BF23E9A51F67055FF0ABEB295C476FC3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Core;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Core.ConditionalFormatting;
using DevExpress.Xpf.Core.DataSources;
using DevExpress.Xpf.Core.Serialization;
using DevExpress.Xpf.Core.ServerMode;
using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.DemoBase.DataClasses;
using DevExpress.Xpf.DemoBase.Helpers;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.ConditionalFormatting;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.Themes;
using DevExpress.Xpf.Grid.TreeList;
using GridDemo;
using System;
using System.Collections;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace GridDemo {
    
    
    /// <summary>
    /// ManagingLiveData
    /// </summary>
    public partial class ManagingLiveData : GridDemo.GridDemoModule, System.Windows.Markup.IComponentConnector {
        
        
        #line 26 "..\..\..\Modules\ManagingLiveData.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit chkAllowUpdating;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\Modules\ManagingLiveData.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ListBoxEdit updateModeList;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\Modules\ManagingLiveData.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit memoryUsageCheckBox;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\Modules\ManagingLiveData.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit cpuUsageCheckBox;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\Modules\ManagingLiveData.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit newRowCheckBox;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\Modules\ManagingLiveData.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit deleteRowCheckBox;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\Modules\ManagingLiveData.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl grid;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\Modules\ManagingLiveData.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.TableView view;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/GridDemo;component/modules/managinglivedata.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Modules\ManagingLiveData.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.chkAllowUpdating = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            
            #line 26 "..\..\..\Modules\ManagingLiveData.xaml"
            this.chkAllowUpdating.Checked += new System.Windows.RoutedEventHandler(this.CheckBox_Checked);
            
            #line default
            #line hidden
            
            #line 26 "..\..\..\Modules\ManagingLiveData.xaml"
            this.chkAllowUpdating.Unchecked += new System.Windows.RoutedEventHandler(this.CheckBox_Unchecked);
            
            #line default
            #line hidden
            return;
            case 2:
            this.updateModeList = ((DevExpress.Xpf.Editors.ListBoxEdit)(target));
            
            #line 29 "..\..\..\Modules\ManagingLiveData.xaml"
            this.updateModeList.EditValueChanged += new DevExpress.Xpf.Editors.EditValueChangedEventHandler(this.updateModeList_EditValueChanged);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 41 "..\..\..\Modules\ManagingLiveData.xaml"
            ((DevExpress.Xpf.DemoBase.SliderControl)(target)).ValueChanged += new System.EventHandler(this.maxCountSlider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.memoryUsageCheckBox = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            return;
            case 5:
            this.cpuUsageCheckBox = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            return;
            case 6:
            this.newRowCheckBox = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            return;
            case 7:
            this.deleteRowCheckBox = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            return;
            case 8:
            this.grid = ((DevExpress.Xpf.Grid.GridControl)(target));
            
            #line 55 "..\..\..\Modules\ManagingLiveData.xaml"
            this.grid.CustomUnboundColumnData += new DevExpress.Xpf.Grid.GridColumnDataEventHandler(this.grid_CustomUnboundColumnData);
            
            #line default
            #line hidden
            return;
            case 9:
            this.view = ((DevExpress.Xpf.Grid.TableView)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

