using DevExpress.Xpf.Core;
using DevExpress.Xpf.DemoBase;

namespace ControlsDemo.TabControl.WebBrowser {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/TabControl.WebBrowser/MainView.xaml",
        "Modules/TabControl.WebBrowser/MainViewModel.(cs)",
        "Modules/TabControl.WebBrowser/WebBrowserView.xaml",
        "Modules/TabControl.WebBrowser/WebBrowserViewModel.(cs)")]
    public partial class MainView : ControlsDemoModule {
        public MainView() {
            InitializeComponent();
        }
    }
}
