using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.Ribbon;

namespace RibbonDemo {
    [NoAutogeneratedCodeFiles]
    public class RibbonTabletOffice : RibbonSimplePad {
        public RibbonTabletOffice() { }

        protected override RibbonTitleBarVisibility GetTitleBarVisibility() {
            return RibbonTitleBarVisibility.Collapsed;
        }
        protected override RibbonStyle GetRibbonStyle() {
            return RibbonStyle.TabletOffice;
        }
    }
}
