using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using DevExpress.Xpf.Grid;
using DevExpress.Data;
using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.Editors.Settings;
using System.Globalization;
using DevExpress.Xpf.Editors;
using DevExpress.XtraExport.Helpers;
using DevExpress.Xpf.Grid.Printing;

namespace GridDemo {
    [CodeFile("Controls/SalesByYearData.cs")]
    public partial class FixedBands : GridDemoModule {
        protected override bool AllowWYSIWYGExport {
            get { return false; }
        }

        public FixedBands() {
            InitializeComponent();
        }

        protected override IGridViewFactory<ColumnWrapper, RowBaseWrapper> GetReportView() {
            return null;
        }

        void grid_AutoGeneratedColumns(object sender, RoutedEventArgs e) {
            grid.Bands[0].Fixed = FixedStyle.Left;
            GridControlBand band = new GridControlBand() { Header = "Total", Fixed = FixedStyle.Right };
            band.Columns.Add(new GridColumn() { FieldName = "Total", UnboundType = UnboundColumnType.Decimal, ReadOnly = true });
            grid.Bands.Add(band);

            grid.BeginDataUpdate();
            SpinEditSettings editSettings = new SpinEditSettings() {
                        MaskType = MaskType.Numeric, Mask = "c", MaskCulture = new CultureInfo("en-US"),
                        MaskUseAsDisplayFormat = true, HorizontalContentAlignment = EditSettingsHorizontalAlignment.Right
            };
            foreach(GridColumn column in grid.Columns) {
                if(column.FieldName != "Employee") {
                    grid.TotalSummary.Add(new GridSummaryItem() { FieldName = column.FieldName, SummaryType = SummaryItemType.Sum });
                    column.EditSettings = editSettings;
                }
            }
            grid.EndDataUpdate();
        }

        void grid_CustomUnboundColumnData(object sender, GridColumnDataEventArgs e) {
            int sum = 0;
            foreach(GridColumn column in grid.Columns) {
                if(column.FieldName != "Employee" && column.FieldName != "Total")
                    sum += (int)e.GetListSourceFieldValue(column.FieldName);
            }
            e.Value = sum;
        }
    }
}
